#!/usr/bin/env bash
# Hoplite fresh-sandbox setup — deps + local PostgreSQL (dev/preview DB and
# integration-test DB). Idempotent: safe to re-run in any sandbox.
set -euo pipefail
cd "$(dirname "$0")/.."

pnpm install --frozen-lockfile
pnpm exec prisma generate

# PostgreSQL 16 ships with the sandbox image; start the cluster if stopped.
if ! pg_isready -q -h 127.0.0.1 -p 5432; then
  service postgresql start >/dev/null 2>&1 || true
  for _ in $(seq 1 15); do
    pg_isready -q -h 127.0.0.1 -p 5432 && break
    sleep 1
  done
fi
pg_isready -q -h 127.0.0.1 -p 5432 || { echo "[setup] local PostgreSQL unavailable" >&2; exit 1; }

# ros_local = dev/preview database; ros_test = integration-test database
# (test-database-guard requires TEST_DATABASE_URL to differ from DATABASE_URL).
sudo -u postgres psql -v ON_ERROR_STOP=1 >/dev/null <<'SQL'
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ros') THEN
    CREATE ROLE ros LOGIN PASSWORD 'ros_local_dev';
  END IF;
END $$;
SQL
for db in ros_local ros_test; do
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname = '${db}'" | grep -q 1 \
    || sudo -u postgres createdb -O ros "${db}"
done

# Local-only env (gitignored) — sandbox-generated, never committed.
if [ ! -f .env.local ]; then
  cat > .env.local <<'EOF'
# LOCAL SANDBOX DEV CONFIG — generated by .hoplite/setup.sh (gitignored)
DATABASE_URL="postgresql://ros:ros_local_dev@127.0.0.1:5432/ros_local"
DIRECT_URL="postgresql://ros:ros_local_dev@127.0.0.1:5432/ros_local"
DATABASE_POOL_MAX="10"
SESSION_SECRET="local-dev-session-secret-0123456789abcdef0123456789abcdef"
CREDENTIAL_ENCRYPTION_KEY="local-dev-credential-key-0123456789abcdef0123456789"
CRON_SECRET="local-dev-cron-secret-0123456789abcdef0123456789abcd"
APP_URL="http://localhost:3000"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
TENANT_ROOT_DOMAIN="roastd.id"
NEXT_PUBLIC_TENANT_ROOT_DOMAIN="roastd.id"
STUDIO_LATEST_VERSION=0.10.2
EOF
fi

# Schema for both databases (prisma CLI resolves DIRECT_URL first — see
# prisma.config.ts — so the test DB is addressed explicitly).
pnpm exec prisma migrate deploy
DIRECT_URL="postgresql://ros:ros_local_dev@127.0.0.1:5432/ros_test" \
  pnpm exec prisma migrate deploy

# Seed the demo roastery into the dev DB only when empty (seed is not
# idempotent). Integration tests manage their own ros_test fixtures.
tenant_count=$(PGPASSWORD=ros_local_dev psql -h 127.0.0.1 -U ros -d ros_local -tAc \
  "SELECT count(*) FROM tenants;" | tr -d '[:space:]')
if [ "${tenant_count}" = "0" ]; then
  pnpm seed
fi
